//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceConsole.MindBody.SiteService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Name="Site ServiceSoap", Namespace="http://clients.mindbodyonline.com/api/0_5_1", ConfigurationName="WebServiceConsole.MindBody.SiteService.SiteServiceSoap")]
    public interface SiteServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute()]
        void GetSites();
        
        [System.ServiceModel.OperationContractAttribute()]
        void GetSitesAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void GetLocations();
        
        [System.ServiceModel.OperationContractAttribute()]
        void GetLocationsAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void GetActivationCode();
        
        [System.ServiceModel.OperationContractAttribute()]
        void GetActivationCodeAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void GetPrograms();
        
        [System.ServiceModel.OperationContractAttribute()]
        void GetProgramsAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void GetSessionTypes();
        
        [System.ServiceModel.OperationContractAttribute()]
        void GetSessionTypesAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void GetResources();
        
        [System.ServiceModel.OperationContractAttribute()]
        void GetResourcesAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void GetRelationships();
        
        [System.ServiceModel.OperationContractAttribute()]
        void GetRelationshipsAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void GetResourceSchedule();
        
        [System.ServiceModel.OperationContractAttribute()]
        void GetResourceScheduleAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void ReserveResource();
        
        [System.ServiceModel.OperationContractAttribute()]
        void ReserveResourceAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void GetMobileProviders();
        
        [System.ServiceModel.OperationContractAttribute()]
        void GetMobileProvidersAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void GetProspectStages();
        
        [System.ServiceModel.OperationContractAttribute()]
        void GetProspectStagesAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void GetGenders();
        
        [System.ServiceModel.OperationContractAttribute()]
        void GetGendersAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SiteServiceSoapChannel : WebServiceConsole.MindBody.SiteService.SiteServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SiteServiceSoapClient : System.ServiceModel.ClientBase<WebServiceConsole.MindBody.SiteService.SiteServiceSoap>, WebServiceConsole.MindBody.SiteService.SiteServiceSoap
    {
        
        public SiteServiceSoapClient()
        {
        }
        
        public SiteServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public SiteServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public SiteServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public SiteServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public void GetSites()
        {
            base.Channel.GetSites();
        }
        
        public void GetSitesAsync()
        {
            base.Channel.GetSitesAsync();
        }
        
        public void GetLocations()
        {
            base.Channel.GetLocations();
        }
        
        public void GetLocationsAsync()
        {
            base.Channel.GetLocationsAsync();
        }
        
        public void GetActivationCode()
        {
            base.Channel.GetActivationCode();
        }
        
        public void GetActivationCodeAsync()
        {
            base.Channel.GetActivationCodeAsync();
        }
        
        public void GetPrograms()
        {
            base.Channel.GetPrograms();
        }
        
        public void GetProgramsAsync()
        {
            base.Channel.GetProgramsAsync();
        }
        
        public void GetSessionTypes()
        {
            base.Channel.GetSessionTypes();
        }
        
        public void GetSessionTypesAsync()
        {
            base.Channel.GetSessionTypesAsync();
        }
        
        public void GetResources()
        {
            base.Channel.GetResources();
        }
        
        public void GetResourcesAsync()
        {
            base.Channel.GetResourcesAsync();
        }
        
        public void GetRelationships()
        {
            base.Channel.GetRelationships();
        }
        
        public void GetRelationshipsAsync()
        {
            base.Channel.GetRelationshipsAsync();
        }
        
        public void GetResourceSchedule()
        {
            base.Channel.GetResourceSchedule();
        }
        
        public void GetResourceScheduleAsync()
        {
            base.Channel.GetResourceScheduleAsync();
        }
        
        public void ReserveResource()
        {
            base.Channel.ReserveResource();
        }
        
        public void ReserveResourceAsync()
        {
            base.Channel.ReserveResourceAsync();
        }
        
        public void GetMobileProviders()
        {
            base.Channel.GetMobileProviders();
        }
        
        public void GetMobileProvidersAsync()
        {
            base.Channel.GetMobileProvidersAsync();
        }
        
        public void GetProspectStages()
        {
            base.Channel.GetProspectStages();
        }
        
        public void GetProspectStagesAsync()
        {
            base.Channel.GetProspectStagesAsync();
        }
        
        public void GetGenders()
        {
            base.Channel.GetGenders();
        }
        
        public void GetGendersAsync()
        {
            base.Channel.GetGendersAsync();
        }
    }
}
